version: '3.8'

services:
  web:
    build: .
    ports:
      - "6543:6543"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/streamMovieDb
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
      - ./public/assets:/usr/src/app/public/assets
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=streamMovieDb

volumes:
  mongodb_data:

